/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119478-g3f94201324-20250514"
#endif /* AVUTIL_FFVERSION_H */
